dask_cluster_kwargs:
  account: m4632
  queue_name: premium
  n_nodes: 1
  n_tasks_per_node: 128
  wallclock: 06:00:00
  scheduler_file: null

notebooks:
  - title: C-SON Skill Assessment
    name: skill-assessment
    use_dask_cluster: false    
    description: "Comparison of model solutions to observational metrics."
    children:
    - pm_compare-to-glodap.ipynb:
      parameters:
        domain_name: "CCS-12km"
        grid_name: "ccs-12km"
        model_name: "cson_roms-marbl_v0.1"
      output_path: outputs/papermill/pm_compare-to-glodap_cson_roms-marbl_v0.1_ccs-12km.ipynb