dask_cluster_kwargs:
  account: m4632
  queue_name: premium
  n_nodes: 1
  n_tasks_per_node: 128
  wallclock: 06:00:00
  scheduler_file: null

notebooks:
  - title: Movie Maker  
    name: movie-maker
    use_dask_cluster: false    
    description: "Create a movie of a variable over time."
    children:
    - pm_movie-maker.ipynb:
      parameters:
        domain_name: "CCS-12km"
        varname: "pCO2SURF"      
        model_name: "cson_roms-marbl_v0.1"
        grid_name: "ccs-12km"
        fps: 6
      output_path: outputs/papermill/pm_movie-maker_cson_roms-marbl_v0.1_ccs-12km_pCO2SURF.ipynb